JuliaParallel/Dagger.jl

src/layout.jl

Changed to iteration over input object.

Fix Hash Layout

---

src/layout.jl

Fixed Bcast export

---

src/file-io.jl
src/ui/graph.jl

Small touch-ups to improve the compatibility with Julia 0.6.

replace takebuf_array with take!

---

src/array/alloc.jl

A minor refactoring I noticed while reading it.

refactor Dagger.stage for AllocateArray

---

src/array/darray.jl
src/chunks.jl
test/array.jl

fix few race conditions in chunk management

---

src/array/darray.jl

use already computed chunks in collect of DArray and avoid double computing

use already computed chunks in collect of DArray

---

src/scheduler.jl

These changes remove the biggest inefficiencies in computing a DAG with a large number of tasks. For example, the following benchmark runs in about 6.5-7.0 seconds before the change, and runs in about 1.0 seconds with the PR.
```
addprocs(4)
using Dagger
@everywhere function spin()
a = 0.0
for i in 1:5000000
a = sqrt(i)
end
return a
end
function main(n)
op = delayed(spin)
leafs = [op() for i in 1:n]
result = delayed((args...)->nothing)(leafs...)
compute(result)
end
main(10)
@time main(1000)
```
As a comparison, this workflow implemented without Dagger (using spawned workers that consume a `RemoteChannel`) runs in about 0.7 seconds on my machine.

Improve efficiency of pop_with_affinity! when there are many tasks

---

src/fault-handler.jl
src/scheduler.jl

Including fault tolerance docs that I should've added previously...

Add some scheduler documentation

---

Project.toml

Bump to 0.9.0

---

src/chunks.jl
src/thunk.jl

Fix ambiguity in unrelease

---

src/scheduler.jl

Per discussion with @DrChainsaw, there's no good reason to serialize the context or processor to another node, and doing so is becoming increasingly more expensive.

Don't serialize ctx or proc to workers

---

src/array/matrix.jl
test/array.jl

Thanks to @alanedelman for spurring this fix :smile:

Add DArray positive integer powers

---

docs/src/index.md
src/thunk.jl
test/runtests.jl
test/thunk.jl

Add at-par macro

---

src/processor.jl
src/scheduler.jl
test/processors.jl

Helpful for dispatching on Processor from within a Thunk

Add TLS accessor for processor in Thunk

---

.buildkite/pipeline.yml
README.md

There's no coverage submission from within Buildkite so I took away that badge. I can try to get it working later though.

Fix readme badges, print out version in nightly

---

.buildkite/pipeline.yml

The previous version should work, but apparently it doesn't, and the nightly test is running Julia 1.5 (you can see it in the stacktrace [here](https://buildkite.com/julialang/dagger-dot-jl/builds/22#d678a78e-8343-42c8-b820-28497f4652f3/18-248)).
This one ought to do the trick.
edit: this revealed that the download of nightly is broken, don't merge this until I fix that
edit2: working now

Actually test on nightly

---

src/compute.jl

Switches `dependents` and `noffspring` from a recursive implementation to a visitor implementation.
Closes #179 
TODO: Also fix `order` and benchmark

Optimize scheduler init

---

src/sch/Sch.jl
src/thunk.jl
test/scheduler.jl

Meta thunks run normally

---

src/Dagger.jl
src/processor.jl
src/sch/Sch.jl
test/processors.jl
test/runtests.jl
test/scheduler.jl

Simplify OSProc

---

.github/workflows/Documentation.yml
.gitignore
Project.toml
README.md
docs/make.jl
docs/src/api/functions.md
docs/src/api/types.md
src/array/darray.jl
src/chunks.jl
src/file-io.jl
src/processor.jl
src/sch/Sch.jl
src/thunk.jl

I have expanded the documentation a little to get this package on the road to having good, reliable docs.  Mainly what I have done here is add an API section to the doc that lists documented types, functions and macros in the package.  I tried to model what I did off of DataFrames.jl which has particularly complete and excellent documentation.
Note that I have added *very little* to the actual content of the documentation.  I did this when going through the package a bit to see how it works, but I am certainly not a regular contributor to this package so my knowledge of its internals is quite poor.
Hopefully, this can serve as a starting point to make it easier for more knowledgeable contributors to make more complete docs.

toward full documentation

---

.ci/test.jl
.github/workflows/ci-julia-1.6-nightly.yml
Project.toml
src/sch/Sch.jl
src/sch/clocks.jl

Temp. fix for clocks on non-Linux

---

Project.toml
src/sch/Sch.jl
test/thunk.jl

Fix task stalls due to deserialization errors

---

src/Dagger.jl
src/table/dtable.jl
src/table/gdtable.jl
src/table/operations.jl
src/table/tables.jl
test/table.jl

[DTable] Tables.jl - dtable as a source

---

docs/src/api/functions.md
docs/src/api/types.md

docs: Add DTable functions/types to API docs

---

src/lib/logging.jl
src/processor.jl
src/sch/Sch.jl
src/sch/util.jl

Reduces some inference time caused by unnecessary specializations, found with https://github.com/shashi/FileTrees.jl/issues/63#issuecomment-1043643936.

Sch,TTFX: Reduce more inference costs

---

.github/workflows/TagBot.yml

This stops running a useless job every single hour.

Switch to new TagBot

---

src/thunk.jl
test/thunk.jl

at-spawn: Synchronize with at-sync

---

Project.toml
src/array/darray.jl
src/chunks.jl
src/compute.jl
src/sch/Sch.jl

Remove `poolset` kwarg that doesn't exist anymore

---

src/sch/Sch.jl

Sch: Fix Some{Any} in CHUNK_CACHE

---

docs/make.jl
docs/src/darray.md

This pull request adds `DArray` documentation.

Add DArray documentation

---

.buildkite/pipeline.yml
Manifest.toml
Project.toml
src/Dagger.jl
src/utils/caching.jl
test/cache_setup_test.jl
test/diskcaching.jl
test/runtests.jl

adds `enable_disk_caching!` which sets up disk caching on every process

`enable_disk_caching` function for handling MemPool storage setup

---

.github/workflows/CompatHelper.yml
Manifest.toml
Project.toml

Add CompatHelper, UB StatsBase to 0.34

---

.buildkite/pipeline.yml
.github/workflows/Documentation.yml
Manifest.toml
Project.toml
src/Dagger.jl
src/options.jl

Also lower bounds Julia to 1.8, as required by ScopedValues.jl
@vchuravy

Use ScopedValues instead of ContextVariablesX

---

src/sch/eager.jl
src/submission.jl
test/thunk.jl

Partially fixes https://github.com/JuliaParallel/Dagger.jl/issues/431

submission: Call init_eager on worker 1

---

src/sch/Sch.jl

processor_runner: Fix race in collect proc_states

---

src/lib/util.jl

I don't know why someone wanted to export these...

Don't export Bytes constants

---

src/chunks.jl

Which is especially beneficial when constructing distributed shards.
Fixes https://github.com/JuliaParallel/Dagger.jl/issues/473

`@shard`: Construct shards in parallel

---

src/lib/domain-blocks.jl

Remove more invalidations

---

src/precompile.jl

Found and fixed thanks to @eschnett
Fixes #501

precompile: Don't let throwto hang the root task

---

test/runtests.jl

This is useful when testing if you don't need extra workers and don't want to wait for them to be started.

Add option to the tests for setting the number of workers

---

src/array/darray.jl

Fixes missing elements in `show` of `DMatrix`

DArray: Fix DMatrix show elements

---

src/sch/Sch.jl

Should fix https://github.com/JuliaParallel/Dagger.jl/issues/536

Sch: Halt on Julia exit

---

src/array/cholesky.jl
src/datadeps.jl

Also adds a warning to Datadeps when multi-worker multi-GPU is attempted, as this functionality is currently broken for unknown reasons.

Minor fixes to Datadeps for GPUs

---

.buildkite/pipeline.yml
Project.toml
docs/src/darray.md
src/Dagger.jl
src/array/linalg.jl
src/array/lu.jl
test/array/linalg/cholesky.jl
test/array/linalg/lu.jl
test/runtests.jl

LU implementation for DArray

---

src/cancellation.jl

Make Dagger.cancel!() handle a shutting down/shutdown scheduler

---

ext/AbstractFFTsExt.jl

Solves https://github.com/JuliaParallel/Dagger.jl/issues/647

change `div` to `cld` to avoid DivideError in FFT
