- src/compute-nodes.jl
Instead of creating a MapPartNode for the `FilterNode`, create it for the input node of the `FilterNode`. This prevents the infinite loop in #3.
> Fix #3 by fixing infinite loop

- src/compute-nodes.jl
This fixes the operation error that was occurring in #6.
2 changes made in this PR are:
1. Splat arguments to the `mapreduce` call.
2. Apply the reduce operation, `op` rather than the map function `f` to the mapped parts.
> Fix reduce

- REQUIRE
- examples/count.jl
- examples/filewc.jl
- src/ComputeFramework.jl
- src/accumulator.jl
- src/compute-nodes.jl
- src/dist-memory.jl
- Getting accumulator id with `rand` can potentially overwrite another valid accumulator, very easily when the random seed is reset for some reason. Using a one up counter instead.
- New method to clear accumulators. Otherwise they leak memory (self-referenced in a global dict)
Also:
- remove Julia 0.5 deprcation warnings (use Compat)
- add wordcount on files to examples (by @shashi)
> fix accumulators

- src/show.jl
- test/runtests.jl
- test/show.jl
Couldn't show the `mapredure` from the readme.
I couldn't run the test on either 0.4 and 0.5, but I had to give up on fixing that. It might be a good idea to enable Travis testing and code coverage.
> Use isa instead of typeof in show

- REQUIRE
Trying to use the package if Logging isn't installed raises a LoadError.
> Update REQUIRE to include Logging

- src/array/alloc.jl
- src/array/matrix.jl
- src/array/operators.jl
- src/compute.jl
- src/domain.jl
- src/file-io.jl
- src/map-reduce.jl
- src/part.jl
- src/partition.jl
- src/read-delim.jl
- src/show.jl
- src/sparse.jl
- test/array.jl
I've added a generic children function that returns the `children` field for `DomainBranch` and indices for the other `Domain` sub-types.
This should prevent `stage` from relying on all Domain sub-types having a `children` field. (#21)
> Added generic children function

- src/part.jl
Rename variable to avoid overwriting the function `parts`.
> fix name conflict in parts.jl

- README.md
- src/ComputeFramework.jl
- src/array/operators.jl
- src/compute.jl
- src/logging.jl
- src/part.jl
- src/partition.jl
- src/processor.jl
- src/util.jl
See docs in README
This is also going to be the basis of the performance UI. One can create many types of `log_sink` objects (arrays, channels, remotechannels) to aggregate metadata about small chunks of work occurring in parallel. You can collect profiling samples from select events and pretty-print them.
I am trying to understand why this stuff is so slow with profiling turned on.
cc @ViralBShah
> timing and profiling

- src/array/alloc.jl
- src/array/map-reduce.jl
- src/array/matrix.jl
- src/array/operators.jl
- src/array/show.jl
- src/basics/compute.jl
- src/basics/data.jl
- src/basics/domain.jl
- src/basics/file-io.jl
- src/basics/partition.jl
- src/lib/blocked-domains.jl
- test/array.jl
- Introduces new `BlockedDomains <: AbstractArray` type which stores blocked distribution as a vector of cumulative lengths along each dimension. Benefits: wayy lesser possible inconsistent states, faster, safer to search for things in.
- delete old code with `@generated` and complicated code to do with plain array of domains
- Distribute now holds the distribution instead of partition type
- Cat no more holds the partition - lots of awkwardness removed.
- GetIndex now has more features (repeated indices, random order), and is faster (asymptotically `O(area)` to `O(log(perimeter))`, for lookups if that makes sense))
- tests for getindex
> Improvements to domain bookkeeping and getindex

- src/basics/file-io.jl
- src/ui/graph.jl
* Return ComputedArray when loading binary files
* Fix depwarns `isgeneric` -> `isa(f, Function)`
> Some possible fixes

- src/Dagger.jl
- src/array/darray.jl
- src/array/sort.jl
- src/compute.jl
- src/scheduler.jl
- src/thunk.jl
- src/ui/graph.jl
- test/array.jl
- test/runtests.jl
creating a PR to make this easy to review.
-----------------------------------
updating some details:
This makes the dag scheduler and executor a configurable module, with the existing implementation included as the default.
A scheduler/executor module must implement:
- `compute_dag(ctx, d::Dagger.Thunk)`: schedules the dag, waits for the top node (`d`) and returns its result
- `cleanup(ctx)`: cleans up any state/IPC before process exit
To switch to a different implementation, set the full module name that implements the above methods in the plugin config. E.g:
```
Dagger.PLUGIN_CONFIGS[:scheduler] = "MyCustomModule.MyScheduler"
```
Apart from that this PR also includes:
- Add the thunk or chunk id to the label when visualizing dag with `show_plan`
- Option not to use shared arrays (in …
> make the scheduler configurable

- src/array/darray.jl
- src/chunks.jl
- test/array.jl
This fixes #79.
Reasons for #79:
- Reference ounting for chunk needs to be done centrally. Isolated reference counting at each worker can lead to a case where one worker loses all refererences and tries to deallocate chunks while other workers are still holding references.
- Sending a DArray reference to a remote process can trigger a `free!` even before the other end has deserialized it.
- Finalizers are not re-established after a serialization - deserialization. (https://github.com/JuliaLang/julia/issues/16667)
This fixes that with:
- custom serializer that increments refcount before serialization
- custom deserializer that adds back the finalizer
- chunk reference counting is done at the origin of the chunk
This still does not address:
- multiple deserializations from the same …
> fix darray chunk refcount to survive serialization

- src/scheduler.jl
The cache option is broken due to `unrelease` not being imported.  This PR fixes the issue.
Error from running the `cache.jl` test.
```
$ julia cache.jl 
cache: Error During Test
Test threw an exception of type UndefVarError
Expression: -s1 == collect(sum2)
UndefVarError: unrelease not defined
Stacktrace:
[1] fire_task!(::Dagger.Context, ::Dagger.Thunk, ::Dagger.OSProc, ::Dagger.Sch.ComputeState, ::Channel{Any}, ::Function) at /Users/tomkwong/.julia/v0.6/Dagger/src/scheduler.jl:127
[2] compute_dag(::Dagger.Context, ::Dagger.Thunk) at /Users/tomkwong/.julia/v0.6/Dagger/src/scheduler.jl:35
[3] compute(::Dagger.Context, ::Dagger.Thunk) at /Users/tomkwong/.julia/v0.6/Dagger/src/compute.jl:26
[4] collect(::Dagger.Thunk) at /Users/tomkwong/.julia/v0.6/Dagger/src/compute.jl:10
[5] macro …
```
> import unrelease function for fire_task! function

- src/array/sort.jl
- test/array.jl
- test/runtests.jl
Update for working around julialang issue https://github.com/JuliaLang/julia/issues/26699 when running across multiple machines.
Also reordered the `if` conditions to have the expensive part (`remotecall`) as the last one.
> do not pass pid 1 as first pid to `check_same_host`

- src/chunks.jl
- test/array.jl
return processor affinity (as given out by MemPool.jl) and size in `affinity` method if `FileRef` has not been read anywhere yet
> implement affinity for unread FileRefs

- src/array/darray.jl
- test/array.jl
Overriding deserialization of DArray introduced in #80 cause the below error:
```
xret = CapturedException(StackOverflowError(), Any[(deserialize(::SerializationState{IOStream}, ::Type{Dagger.DArray{Any,2,Base.#cat}}) at darray.jl:117, 100)])
DArray constructor: Error During Test
Got an exception of type StackOverflowError outside of a @test
StackOverflowError:
Stacktrace:
[1] deserialize(::SerializationState{IOStream}, ::Type{Dagger.DArray{Any,2,Base.#cat}}) at /home/tan/.julia/v0.6/Dagger/src/array/darray.jl:117 (repeats 20000 times)
```
Strangely the tests had passed then.
This is to avoid the stack overflow error. I did not find any other mechanism to invoke a specific method instance.
Also included a change in tests to have it pass when `Dagger.use_shared_array[] == false`.
> avoid stackoverflow in deserialize

- .travis.yml
- REQUIRE
- src/chunks.jl
- test/array.jl
> start off with all workers on the node as affinity to FileRef

- src/lib/util.jl
A simple refactor based on the [style guide](https://docs.julialang.org/en/v1/manual/style-guide/#Do-not-write-x-f(x)-1).
> refactor: simplify map call

- src/array/darray.jl
- src/chunks.jl
- src/scheduler.jl
- src/thunk.jl
- test/array.jl
I now add the finalizer to Chunk objects on deserialization, just like #80. I was being so dumb and benchmarking finalizer on Chunks without this and feeling horrified. All this while.
But this poses a new problem which seems only solvable with additional complexity:
```julia
@testset "darray distributed refcount" begin
D2 = remotecall_fetch(2, compute(Distribute(Blocks(10, 20), rand(40,40)))) do D
D2 = D
end
@test size(collect(D2)) == (40,40)
end
```
This test fails because chunks are discarded right after the first line (they get gc'd soon after compute). The collect statement is too late. We may need some refcounting on Chunks to solve this, I was hoping to avoid that.
> wip: Fixes to GC interaction

- src/Dagger.jl
- src/lib/logging.jl
This seems to be sufficient to fix JuliaDB's `tracktime`. However, I'm not sure how to test this properly within Dagger.
> Import procs from Distributed and fix use of foldl

- src/array/sort.jl
- src/scheduler.jl
`rethrow` is no longer allowed outside a catch block. Also another small change I had.
> a fix for julia 1.1

- .gitignore
- Project.toml
- REQUIRE
Added Project.toml and excluded Manifest.toml in gitignore
Bumped Julia version to 1.0 in REQUIRE
Hopefully the `[compat]` line is correct too.
> Lowerbound to Julia 1.0 and add Project.toml

- src/array/darray.jl
- src/chunks.jl
- src/compute.jl
- src/scheduler.jl
- test/runtests.jl
- test/scheduler.jl
This PR allows the scheduler to take options as keyword args. To start with, I'm adding an option called "single" which forces all work onto a single worker (master or a specific worker) by worker id.
> Add configurable options to scheduler

- src/scheduler.jl
- src/thunk.jl
- test/scheduler.jl
- Adds `options` kwarg and field to Thunk
- Adds ThunkOptions to Dagger.Sch
- Renames ComputeOptions to SchedulerOptions to improve clarity
- Added docstrings for both option structs
- Added Thunk options test, changed both options tests `single` to master
I also removed the old tests to address #99, if that's desired.
> Add Thunk options

- src/fault-handler.jl
- src/scheduler.jl
- test/fault-tolerance.jl
- test/runtests.jl
When a worker is killed due to OS signals (such as the Linux OOM
killer), a ProcessExitedException is likely to be thrown to the head
node. When such an exception is detected, we reschedule the failed thunk
on a new, non-dead worker (randomly for now).
Todo:
> Add fault tolerance to scheduler

- src/processor.jl
- src/scheduler.jl
- test/scheduler.jl
1. Spawn `Threads.@spawn f(x...)` instead of `f(x...)` where `x` is the "fetched" data.
2. repeat every process as many times as nthreads() -- causing Dagger to oversubscribe each worker processors as many times as the threads. TOOD: actually get nthreads from each worker rather than using the value on the master process
By @shashi 
Will need to be adjusted so that pre-MT julia still works, and to make this an opt-in feature for now.
> Threading trick!

- src/Dagger.jl
- src/array/darray.jl
- src/array/getindex.jl
- src/array/map-reduce.jl
- src/array/matrix.jl
- src/array/operators.jl
- src/array/setindex.jl
- src/array/sort.jl
- src/chunks.jl
- src/compute.jl
- src/fault-handler.jl
- src/file-io.jl
- src/processor.jl
- src/scheduler.jl
Sorry if this is too much of a mixed bag, would be happy to split it up as well. But it's mostly straightforward.
88d9964ca78a18d2c42e9a134184a588dbaee81e removes empty files
d6aca842107ff2a4fedc865a28daa31c2425a7d0 only touches docstrings
4cd00516c18c1cf2d2953e4e7cdee9d1f190d94c adds argument type annotations, good to double check if all are correct
82c15067199640f9895994fea3e8b8c538cdd89e is a simple do block
a4c409b7737c088250789ec228eb292c12f1e9d2 DArray.concat must be a function right?
d8f4fdee5b10a3cb58e03db2dacfd74dd88b10a2 looks like an oversight
> Polish up docstrings and more

- README.md
- docs/make.jl
> Fix the deployment of the documentation

- .github/workflows/reverse_CI_JuliaDB.yml
Fixes #132 
This PR creates the `reverse_CI_JuliaDB` CI job, which tests Dagger against the latest JuliaDB `master`.
cc: @jpsamaroo
> Set up reverse CI for testing JuliaDB against Dagger

- src/thunk.jl
```
julia> delayed(+)(delayed(sin)(π),  delayed(cos)(delayed(identity)(π)))
Thunk(+, (Thunk(sin, ...), Thunk(cos, ...)))
```
Truncates at 2 levels and just prints "..." in place of arguments.
> add better Thunk printing

- Project.toml
This is what's causing ModelingToolkit test failures: https://travis-ci.com/github/SciML/ModelingToolkit.jl/builds/184324132#L460 . It would be good to get quick tag.
@shashi
> Allow StatsBase 0.33

- Project.toml
- src/chunks.jl
- src/processor.jl
- src/scheduler.jl
- test/fakeproc.jl
- test/processors.jl
- test/scheduler.jl
Fixes #143 
Avoids creation of a new context
If there is a good reason to not pass the context (IC bandwidth?) then perhaps initialize it with myid?
> Remove context from move

- Project.toml
- docs/src/logging.md
- src/compute.jl
- src/processor.jl
- src/scheduler.jl
- src/ui/graph.jl
- test/ui.jl
> Improve UI plan rendering

- Project.toml
- src/array/alloc.jl
- src/chunks.jl
- src/fault-handler.jl
- src/processor.jl
- src/scheduler.jl
- test/array.jl
- test/scheduler.jl
The intent of this PR is to inform the scheduler about the "pressure" on each worker, where pressure is some measure of the ability for a worker to compute a thunk in a timely manner. The scheduler is modified to take this pressure into account every time it tries to schedule a thunk, with the scheduler choosing to schedule ready thunks onto the workers with the least amount of relative pressure. We also allow more than just `Nprocs` thunks to be scheduled at a time; instead, we schedule all thunks marked ready. In the future, I intend to expand this approach to schedule full sub-graphs onto each worker to improve data locality.
Currently the tests are failing for various array operations. Whether we end up removing the array operations from this package or not (@shashi), I'd still like …
> Added worker pressure monitoring

- Project.toml
- src/chunks.jl
- src/processor.jl
- src/scheduler.jl
- src/ui/graph.jl
- test/fakeproc.jl
- test/processors.jl
- test/scheduler.jl
- test/ui.jl
We've been doing something *real bad*, and eagerly fetching thunk arguments from `Chunk`/`DRef`s, which is totally not the intent of the Processors system. This PR corrects that by changing the API of `choose_processor` and `iscompatible` to operate on types instead, and ensuring that `Chunk`s always store the real type of the wrapped argument (instead of `Any`). Subtypes of `Processor` are now expected to handle `Chunk`s manually if they want to use special methods to transfer their contained data (by default, they'll be unwrapped and moved over the regular cluster network via serialization).
Fixes #162 
Todo:
> Make argument fetching asynchronous

- Project.toml
- docs/make.jl
- docs/src/dynamic.md
- src/Dagger.jl
- src/processor.jl
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/sch/fault-handler.jl
- src/sch/util.jl
- src/thunk.jl
- test/processors.jl
- test/scheduler.jl
Allow thunks to dynamically control the scheduler
Todo:
> Add dynamic scheduler control

- .gitignore
- src/sch/Sch.jl
- test/scheduler.jl
When we "finish" a thunk (mark it completed), we immediately assign the processor some work based on how close the data is to the worker. Sometimes, we'll even refuse to schedule if we don't think the worker should have a given piece of work. Over time, the worker accrues so much of the work, that it also accrues most of the output data, and then ends up getting stuck being the only worker doing anything. In a sense, the scheduler is being overly conservative about data transfer costs, and failing to consider compute costs.
> Remove immediate_next fast-path

- Project.toml
- docs/src/index.md
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/sch/eager.jl
- src/sch/fault-handler.jl
- src/sch/util.jl
- src/thunk.jl
- test/runtests.jl
- test/scheduler.jl
- test/thunk.jl
- test/util.jl
The macro `Dagger.@spawn` is similar to `Dagger.@par`, however it schedules work "eagerly"; that is to say, the generated thunk(s) are immediately placed on an active scheduler. Dagger will now start up a scheduler instance in the background for such thunks, and will remain available for the full Julia session.
The intent is to mimic Base's `@async` and `Threads.@spawn`, allowing functionally-written code to be executed in a distributed manner without having to "thread" Dagger through a codebase.
Todo:
> Add at-spawn macro for eager scheduling

- docs/src/index.md
- docs/src/processors.md
- src/processor.jl
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/sch/eager.jl
- src/sch/fault-handler.jl
- test/processors.jl
- test/runtests.jl
- test/scheduler.jl
- test/thunk.jl
Supersedes #171 
This should allow better usage of GPUs via DaggerGPU, especially when operating with one GPU per process.
Todo:
> Extend proctypes to callables, track utilization

- Project.toml
- docs/src/index.md
- src/processor.jl
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/sch/eager.jl
- src/thunk.jl
- test/thunk.jl
@tkf @DhairyaLGandhi
Closes #215
> Add Dagger.spawn, allow on any node

- Project.toml
- benchmarks/benchmark.jl
- benchmarks/visualize.jl
- src/chunks.jl
- src/compute.jl
- src/lib/logging.jl
- src/processor.jl
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/sch/fault-handler.jl
- src/sch/unix.jl
- src/sch/util.jl
- src/ui/gantt-server.jl
- src/ui/gantt.jl
- test/processors.jl
- test/scheduler.jl
- test/util.jl
This PR adds runtime estimation of thunk costs (per signature) to get as close to max utilization as possible (without impacting total runtime). It also adds chunk data caches to workers, which will be freed by the scheduler once they're no longer needed.
~Depends on https://github.com/JuliaData/MemPool.jl/pull/49~ Not doing this for now, wrong API for performance reasons.
Closes #205
Todo:
> Thunk cost estimation, chunk caching, benchmark updates

- src/sch/eager.jl
- test/thunk.jl
Parallel dynamic fib requires calling `dynamic_fib(n-2)` before `fetch`. Otherwise, all recursions are done serially.
Maybe it was me who sent this code to @jpsamaroo :)
> Fix dynamic_fib

- Project.toml
- src/Dagger.jl
- src/chunks.jl
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/sch/eager.jl
- src/sch/util.jl
- src/thunk.jl
- test/runtests.jl
- test/scheduler.jl
- test/thunk.jl
We need to ensure that we allow eager-allocated `Thunk`s to become unreferenced by the scheduler when they're no longer needed, so that they and their inputs can be subject to GC.
This also fixes a memory leak caused by the dynamic listener not terminating with its associated scheduler, resulting in a leak of the entire `ComputeState`.
> Fix memory leaks in eager API

- docs/src/checkpointing.md
- src/sch/Sch.jl
- src/sch/util.jl
- test/checkpoint.jl
- test/runtests.jl
- test/util.jl
Lets one return `nothing` from a restore hook to quietly skip the hook.
> Quiet restore failures with nothing result

- Project.toml
- src/sch/Sch.jl
- test/cache.jl
- test/runtests.jl
> Fix bug in lazy API state.errored check

- Project.toml
- src/Dagger.jl
- src/table/dtable.jl
- src/table/iterators.jl
- src/table/operations.jl
- test/runtests.jl
- test/table.jl
> DTable implementation 

- Project.toml
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/sch/eager.jl
- src/sch/fault-handler.jl
- src/sch/util.jl
- src/thunk.jl
> Fix eager API thunk retention

- src/lib/logging.jl
Fixes #268 while working on the new logging system.
> Update `get_logs!` to capture log output from worker 1.

- .buildkite/pipeline.yml
We want to keep the `julia` CI queue dedicated for base julia CI.  If you know of any other projects using the `julia` queue, please make this change in them as well.  :)
> Use `juliaecosystem` CI queue

- docs/make.jl
- docs/src/api/functions.md
- docs/src/api/types.md
- docs/src/dtable.md
- docs/src/index.md
- docs/src/scheduler-internals.md
Fixes some of the poor wording and organization in the documentation, and focuses the documentation on the eager API, rather than the legacy lazy API.
Thanks to @kshyatt (and others over the past few months) for pointing out these much-needed changes!
> docs: Reword and remove garbage

- Project.toml
- docs/src/api/functions.md
- docs/src/dtable.md
- src/Dagger.jl
- src/table/dtable.jl
- src/table/groupby.jl
- src/table/join.jl
- src/table/join_interface.jl
- src/table/operations.jl
- src/table/tables.jl
- test/table.jl
> [DTable] Leftjoin

- src/compute.jl
This avoids the following error which crashes the scheduler:
```
MethodError: defalg(::Vector{Union{}}) is ambiguous. Candidates:
defalg(v::AbstractArray{<:Union{Missing, Number}}) in Base.Sort at sort.jl:658
defalg(::AbstractArray{<:Union{Missing, String1, String15, String3, String7}}) in InlineStrings at /Users/juliauser/.julia/packages/InlineStrings/C5tOh/src/InlineStrings.jl:656
Possible fix, define
defalg(::AbstractArray{<:Missing})
```
When parents is empty in order(), it has type Vector{Union{}}. Since Union{} is a subtype of all
Union{...any types here...} types, any package that defines Base.defalg(AbstractArray{<:Union{...any type...}})
will cause an ambiguity error. This is true even without type piracy, as the Union in the other package could
consist entirely of types defined …
> don't sort! parents when empty in order()

- src/utils/system_uuid.jl
@mattwigway please review if you get the chance
Fixes #316
> Make system UUID determination atomic

- src/sch/Sch.jl
- src/sch/dynamic.jl
> Sch: Start dynamic listener in init_proc

- .buildkite/pipeline.yml
- .github/workflows/ci.yml
- src/compute.jl
- src/processor.jl
- src/sch/Sch.jl
- src/sch/util.jl
- src/thunk.jl
> thunk,Sch: Reduce invalidations and TTFX

- src/sch/Sch.jl
- test/scheduler.jl
As promised earlier, here is an attempt to fix the remove workers test.
It turned out a bit more evil than I had hoped as it was quite difficult to yank the workers after work had started and any alternative suggestions to using the logging framework for this is appreciated.
The change in `Sch` is because you'd otherwise get errors for not having ran `using Dagger` on the workers in the add workers test after it completes.
> Fix remove workers test

- src/sch/dynamic.jl
- src/sch/util.jl
- test/options.jl
- test/scheduler.jl
`dominates` (called in `add_thunk!` -> `register_future!`) previously used a duplicative recursive implementation, which has known issues. This switches `dominates` to a visitor pattern, which results in far better performance on large task trees.
Fixes #341
> add_thunk: Optimize domination check

- lib/DaggerWebDash/src/d3.jl
- src/array/darray.jl
- src/compute.jl
- src/file-io.jl
- src/processor.jl
- src/ui/graph.jl
To allow `delayed` to inherit from a global context, making logging and scheduler visualization easy to configure globally.
> Context: Add global context for lazy API

- src/thunk.jl
- test/thunk.jl
We can't currently support passing `Thunk`s into `@spawn`, so explicitly detect and disallow this for now.
> spawn: Disallow passing Thunk as argument

- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/sch/util.jl
Does some simple optimizations to reduce the overhead of deep and wide DAGs, and `@spawn` in general.
> Minimize overhead of `add_thunk!`

- src/sch/eager.jl
- test/thunk.jl
Prevents warnings from MemPool that it had to forcibly evict references.
> eager: Force kill scheduler on exit

- src/sch/util.jl
Fixes a bug in the storage safety check, where the topmost object isn't directly checked, leading to hitting a (very) slow path.
@krynju
> Add missing check to walk_data

- src/sch/util.jl
Fixes an issue where `Dagger.Sch.signature` captures input arguments, instead of their types.
Thanks to @krynju for putting together a DTables reproducer!
> signature: Don't capture input arguments

- src/chunks.jl
- src/sch/Sch.jl
- src/sch/eager.jl
- src/sch/util.jl
Through the scheduler, a task also retains its inputs through entries in `state.cache`; this is fine for tasks which references other tasks, because we have a `WeakThunk` mechanic to allow those input tasks to be freed when unneeded. However, this didn't apply to `Chunk` objects. This is a simple fix which implements a `WeakChunk` mechanic in the same way, which allows `Chunk` inputs to a completed task to be freed.
> chunks: Allow weak Chunk references in Thunk args

- src/sch/Sch.jl
- src/sch/util.jl
- src/thunk.jl
- test/thunk.jl
Previously, we had an assertion in `schedule!` that a task being scheduled could not already have a cache result, as that seems counterintuitive. However, when an upstream task has thrown an error, downstream tasks are all eagerly tainted by `set_failed!`, which sets their cache value to the `ThunkFailedException` object.
This PR loosens that assertion to ignore errored tasks, and refines the non-erroring case to throw a `SchedulingException` to the task instead.
> Fix incorrect assertion in schedule!

- src/sch/Sch.jl
As reported in https://github.com/JuliaParallel/Dagger.jl/issues/197
> checkpoint: Use at-invokelatest

- Project.toml
- docs/src/index.md
- src/Dagger.jl
- src/processor.jl
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/sch/eager.jl
- src/sch/util.jl
- src/thunk.jl
- src/utils/locked-object.jl
- test/options.jl
Adds logic to do work stealing within and across workers, which can help prevent workload imbalance and processor starvation.
Todo:
> Implement work stealing

- .buildkite/pipeline.yml
- docs/src/checkpointing.md
- docs/src/index.md
- docs/src/propagation.md
- src/array/darray.jl
- src/array/map-reduce.jl
- src/array/matrix.jl
- src/array/operators.jl
- src/array/setindex.jl
- src/compute.jl
- src/processor.jl
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/sch/eager.jl
- src/sch/fault-handler.jl
- src/sch/util.jl
- src/thunk.jl
- src/ui/graph.jl
- test/scheduler.jl
- test/thunk.jl
APIs like `delayed` and `spawn` assumed that passed kwargs were to be treated as options to the scheduler, which is both somewhat confusing for users, and precludes passing kwargs to user functions.
This PR changes those APIs, as well as `@spawn`, to instead pass kwargs directly to the user's function. Options are now passed in an `Options` struct to `delayed` and `spawn` as the second argument (the first being the function), while `@spawn` still keeps them before the call (which is generally more convenient).
Internally, `Thunk`'s `inputs` field is now a
`Vector{Pair{Union{Symbol,Nothing},Any}}`, where the second element of each pair is the argument, while the first element is a position; if `nothing`, it's a positional argument, and if a `Symbol`, then it's a kwarg.
> Add keyword argument support

- .buildkite/pipeline.yml
- src/array/darray.jl
- src/array/map-reduce.jl
- test/array.jl
Previously it would fallback to `Any`, which breaks uses of `eltype(::DArray)`
> DArray: Figure out correct eltype

- src/array/alloc.jl
- src/array/darray.jl
- src/array/operators.jl
- test/array.jl
Adds explicit support for `zero`, `copy`, and `similar`, and changes broadcast to return a `DArray` instead of a `BCast`.
> DArray: Improve DiffEq support

- docs/src/darray.md
- docs/src/index.md
- src/array/alloc.jl
- src/array/darray.jl
- src/array/getindex.jl
- src/array/map-reduce.jl
- src/array/matrix.jl
- src/array/operators.jl
- src/array/sort.jl
- src/sch/Sch.jl
- test/array.jl
Rebase and tweaks of #406, and prep for DaggerMPI support
> DArray: Operations always return DArrays, and add local partition support for MPI

- docs/src/data-management.md
- docs/src/index.md
- src/chunks.jl
- test/mutation.jl
Makes `@mutable` much more useful for distributed computing. Also breaks the multi-argument forms of `@mutable` to allow passing options as key-value pairs before the expression to evaluate.
> at-mutable: Add remote execution like shard

- .github/workflows/CustomCommands.yml
- benchmarks/suites/nmf.jl
So that we can run custom commands on PRs. Some desirable commands including:
Implemented:
- Benchmarks (against `master` or other branches/commits)
- Aqua.jl for overall package quality
Future:
- PropCheck.jl for fuzzing and other stress tests
- PerfChecker.jl for regression testing
- JuliaFormatter.jl for formatting
> TEST: Try implementing custom actions

- src/utils/caching.jl
Should fix https://github.com/JuliaParallel/DTables.jl/issues/34
> disk_caching: Pass Dagger module in remotecall

- Manifest.toml
- Project.toml
- src/Dagger.jl
- src/ui/graph-core.jl
- src/ui/graph.jl
- test/logging.jl
Moves Colors.jl to be a Requires-included dependency, which was taking up a bunch of loading time, as pointed out by @oschulz
> Requires-ify UI deps

- src/file-io.jl
- test/file-io.jl
This PR proposes a fix to a potential bug discovered in https://github.com/JuliaParallel/DTables.jl/issues/35
**Behaviour:** When using relative paths (eg, `Dagger.tofile(data, "data_processed/obj_$i.arrow", ...)`, the directories would be ignored and files would be saved directly in pwd().
**Reason:** Path splitting was done with `isabspath` (see [link](https://github.com/JuliaParallel/Dagger.jl/blob/04e2466a92927faecb9d1c27cf50f5b93bc8df3b/src/file-io.jl#L33), but that doesn't work for relative paths.
Example:
```julia
path = "data_output/out.arrow"
isabspath(path) # false! not helpful if we want to know if we need to use pwd() to set directory!
```
Proposed change:
```julia
dir, file = dirname(path), basename(path)
dir = isempty(dir) ? pwd() : dir
```
I've also added a test case for …
> Update path splitting rule in Dagger.File / Dagger.tofile

- docs/src/data-management.md
On Dagger 0.18.2 for me copy/pasting the sharding example resulted in the error
````
ERROR: MethodError: no method matching getindex(::Dagger.Chunk{Base.Threads.Atomic{Int64}, MemPool.DRef, OSProc, ProcessScope})
Stacktrace:
[1] (::var"#9#10")(ctr::Dagger.Chunk{Base.Threads.Atomic{Int64}, MemPool.DRef, OSProc, ProcessScope})
@ Main ./REPL[6]:2
[2] iterate
@ ./generator.jl:47 [inlined]
[3] collect(itr::Base.Generator{Dagger.Shard, var"#9#10"})
@ Base ./array.jl:782
[4] map(f::Function, A::Dagger.Shard)
@ Base ./abstractarray.jl:3289
[5] top-level scope
@ REPL[6]:2
````
I don't know if my fix is the idiomatic way to do it, but this worked for me at least.
> Fix error in documentation

- src/thunk.jl
- test/thunk.jl
We previously were capturing `Thunk`s in `ThunkFailedException`, which is a totally wrong thing to do (since `Thunk`s aren't safe to serialize, but errors should be serializable everywhere). Now we convert `Thunk` to `ThunkSummary` objects which summarize the relevant details contained in the original `Thunk`, for printing and analysis purposes.
Fixes #430
> ThunkFailedException: Scrub out Thunk

- src/submission.jl
Fixes a bug in the submission logic where we accidentally overwrote a task's local uid with the uid of the task's arguments.
Fixes #435
> submission: Fix variable shadowing bug

- src/chunks.jl
- src/sch/util.jl
- src/submission.jl
Issues fixed:
- Locking was done incorrectly during submission in some circumstances
- Workaround fact that `WeakRef` cannot be serialized safely via `WeakChunk`
- GC retention of pre-submission args was missing
- `Chunk` GC retention was done incorrectly w.r.t `Chunk` hashing behavior
Fixes #437
> Sch: Fix various locking and WeakChunk issues

- src/sch/Sch.jl
- src/sch/util.jl
- src/utils/locked-object.jl
Fixes complaints about `yield`ing in finalizers introduced in https://github.com/JuliaParallel/Dagger.jl/pull/446
> errormonitor_tracked: Use spin lock

- src/Dagger.jl
- src/processor.jl
- src/utils/locked-object.jl
Should fix https://github.com/JuliaParallel/Dagger.jl/issues/453
> OSProc: Add locking around OSPROC_PROCESSOR_CACHE

- src/options.jl
- test/options.jl
An unfortunate bug that was missed in the initial options implementation: options should be merged when nesting `with_options` :scream:
> tests: Test for previous option preservation

- src/Dagger.jl
- src/processor.jl
- src/sch/Sch.jl
- src/utils/tasks.jl
Should fix https://github.com/JuliaParallel/Dagger.jl/issues/459 by retrying `jl_set_task_tid` until it either succeeds, or bailing out after 10 failed attempts.
> Retry jl_set_task_tid on failure

- .buildkite/pipeline.yml
- Manifest.toml
- Project.toml
- src/precompile.jl
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/sch/eager.jl
- src/sch/util.jl
- src/submission.jl
Builds off of https://github.com/JuliaData/MemPool.jl/pull/76 to allow the scheduler to eagerly free cache task results when unneeded (no further user handles to the task, and no more scheduler-internals downstream dependencies on the task). This simply speeds up the process of freeing memory that the GC will already end up freeing on the next cycle.
> Eagerly free Thunk cached results when unneeded

- src/sch/Sch.jl
- test/scheduler.jl
The scheduler chunk cache has been around for a while, but unfortunately was never really correct in the face of mutating data. If data is mutated by any Dagger task, Dagger's chunk cache may still serve the stale, non-mutated data copy. This issue has come up in a number of places, and so it needs to be resolved now before causing further issues. A proper fix is still in the works (as part of a larger set of changes), but in the meantime, this hotfix will have to do.
> Sch: Temporarily disable chunk cache

- src/sch/Sch.jl
Since we've disabled `CHUNK_CACHE` on master
> Sch: Disable CHUNK_CACHE evictions for now

- src/precompile.jl
This should avoid hanging `wait` calls and having to throw exceptions to running tasks during precompile.
> precompile: Slightly lengthen pre-wait timeout

- src/sch/eager.jl
- src/submission.jl
A lot of tests failed when I was running them locally because that variable is defined in the `Dagger` module rather than `Dagger.Sch`. Though a lot still fail for me with this error:
```julia
Got exception outside of a @test                                                                                                                                                                                                             
On worker 2:                                                                                                                                                                                                                                 
Tuple field type cannot be Union{}
```
I think we're running into https://github.com/JuliaLang/julia/issues/52385 :grimacing: I'll …
> Reference Dagger.EAGER_THUNK_STREAMS explicitly

- Manifest.toml
- Project.toml
- docs/src/darray.md
- src/array/alloc.jl
- src/array/map-reduce.jl
- test/array.jl
Improves the behavior of operations based on `mapreduce`, and adds `var`, `std`, and `extrema` operations, while enhancing tests for these and existing operations.
Fixes #475
> DArray: Fixes and improvements for mapreduce operations

- src/submission.jl
This was using the `chunktypes()` API, which I don't think is correct in general. Now all the tests pass for me.
> Special-case StreamingFunction in EagerThunkMetadata() constructor

- src/Dagger.jl
Previously `ScopedValues.with` was exported from `Base` but that was changed recently, so the ScopedValues check was failing. Now we check if the module is present instead.
Should fix #488. I still this warning when running the tests:
```julia
┌ ScopedValues                                                                                                                                                                                                                                 
│  WARNING: could not import ScopedValues.current_scope into ScopedValues                                                                                                                                                                      
└    
```
But we don't use `current_scope()` anywhere so I assume it's …
> Fix import of ScopedValues in Julia v1.11

- docs/src/api-dagger/types.md
- docs/src/scheduler-internals.md
- docs/src/task-spawning.md
- src/eager_thunk.jl
- src/sch/Sch.jl
This mostly just adds the ThunkOptions and SchedulerOptions docstrings to the docs, along with some other minor improvements:
- Enabled showing docstrings for Chunk and Shared
- Added more links to task-spawning.md
- Fixed the formatting of the argument lists in ThunkOptions and SchedulerOptions so they're displayed properly.
> Add options docstrings to the docs

- src/utils/scopes.jl
- test/processors.jl
- test/scopes.jl
Adds a `num_processors()` helper, to assist users and libraries with implementing Dagger-powered parallelism utilities.
Closes https://github.com/JuliaParallel/Dagger.jl/issues/474
> Add num_processors helper

- ext/GraphVizExt.jl
- src/Dagger.jl
- src/array/alloc.jl
- src/array/darray.jl
- src/array/indexing.jl
- src/array/operators.jl
- src/array/sort.jl
- src/array/sparse_partition.jl
- src/chunks.jl
- src/datadeps.jl
- src/sch/Sch.jl
- src/utils/logging-events.jl
TL;DR:
- Replaced all uses of `using` with explicit imports
- Removed old imports
This should be a purely cosmetic change.
> Cleanup imports with ExplicitImports.jl

- README.md
- docs/src/index.md
Also changed the Slack channel reference to `#dagger`.
Fixes #509.
> Add a section to the documentation about code loading

- docs/Project.toml
- docs/make.jl
- docs/src/api-timespanlogging/functions.md
- docs/src/api-timespanlogging/types.md
- docs/src/logging-visualization.md
- ext/GraphVizExt.jl
- ext/PlotsExt.jl
- src/sch/dynamic.jl
- src/utils/logging-events.jl
- src/utils/logging.jl
- src/visualization.jl
Addresses a bug and missing documentation reported in https://github.com/JuliaParallel/Dagger.jl/issues/512. I'm having trouble getting the `GraphVizExt` and `PlotsExt` docstrings to show up in the docs without errors during cross-reference, so this will have to suffice until we figure that out.
> logging/viz: Some fixes, and more docstrings

- src/cancellation.jl
- src/stream-fetchers.jl
This fixes some issues we're seeing in @davidizzle's tests:
- Sometimes the `test_finishes()` test harness will attempt to cancel a task after the scheduler has already exited, causing exceptions.
- The tests would hang at a certain point if debug logging was turned off.
> Test fixes

- src/array/darray.jl
Fixes `DArray`s showing old values or values from other `DArray`s
I'll implement a more robust caching system to replace this with.
> DArray: Fix broken indexing caching

- .buildkite/pipeline.yml
- src/sch/Sch.jl
- src/stream.jl
- test/streaming.jl
This is useful for testing and benchmarking.
BTW I added the `stream_max_evals` option to `SchedulerOptions` and `ThunkOptions`, but I see that the other streaming options are sort of used adhoc and filtered out before being passed upwards. Is that just for quick prototyping? Or should the streaming options go somewhere else?
> Add support for limiting the evaluations of a streaming DAG

- src/array/darray.jl
- test/array/allocation.jl
Fixes a few bugs in 0-dim `DArray` allocation, show, and collect, as reported by @mofeing
> DArray: Improve 0-dim support

- src/sch/Sch.jl
- src/sch/dynamic.jl
I've cherry-picked two commits from the streaming branch that improve handling of dead workers, @mofeing this should fix the errors that you're seeing (in particular 1fa2ea4). Originally added in #496.
> Dead worker handling

- src/thunk.jl
- test/runtests.jl
- test/thunk.jl
Uses MacroTools' `@capture` in the `@spawn` parser to parse calls, and in the process adds support for do-block syntax and direct calls to anonymous functions:
```julia
Dagger.@spawn sum(A) do a
return a+1
end
Dagger.@spawn A->sum(A; dims=1)+2
```
This should make it easier for users to apply `Dagger.@spawn` to arbitrary calls. Note that I am not tackling #514, as that is significantly more difficult to do (it requires finding and transforming all values which might be a `DTask`).
Fixes #480 
Fixes #479
Fixes #421
> parser: Assorted improvements

- src/memory-spaces.jl
- test/datadeps.jl
> aliasing: Add optimized will_alias for views

- src/array/alloc.jl
- src/array/darray.jl
- src/array/mul.jl
This makes it so that `DArray` tile allocations can be dispatched on, such that we can allocate tiles on the GPU when using a DaggerGPU processor.
> DArray: Make allocations configurable via Processor

- benchmarks/suites/dtable.jl
- benchmarks/visualize.jl
- docs/src/datadeps.md
- docs/src/dynamic.md
- docs/src/task-spawning.md
- docs/src/use-cases/parallel-nested-loops.md
- test/processors.jl
Fixed some minor typos in docs, benchmarks and test
> Fix typos in documentation, tests and benchmarks

- docs/src/api-dagger/functions.md
- docs/src/api-dagger/types.md
- docs/src/datadeps.md
The datadeps (`spawn_datadeps`, `In`, `Out`, etc.) have their own usage-page in the docs but weren't mention in the API documentation. The already provided docstrings can be used
I think it would be also useful to add a remark in the documentation that `spawn_datadeps` waits for all the tasks spawned. This part was unclear for me and I had to check the source code
> Include datadeps in API documentation

- FEATURES_ROADMAP.md
- README.md
So that users can see at a glance the support level for available features, as well as the list of features that we'd love contributions for!
> Add a Features/Roadmap document

- src/thunk.jl
- test/thunk.jl
We need to make sure to throw an error if the launched `DTask`s error.
> @spawn: Properly rethrow in @sync

- src/thunk.jl
- test/thunk.jl
Allows for doing things like:
- `Dagger.@spawn (;a=1, b=2)`
- `Dagger.@spawn a.x`
> `@spawn`: Support NamedTuple construction and access

- docs/src/use-cases/parallel-nested-loops.md
Main feature is a warning regarding using `@sync` on inner loops.
There are also some minor grammar fixes to a sentence on the same page, partially thanks to @wolthom for noticing them.
> Warn in docs about sync on inner loops

- Project.toml
- src/Dagger.jl
- src/chunks.jl
- src/thunk.jl
- test/thunk.jl
This is useful for `fetch`ing a collection of `DTask`s or `Chunk`s.
> Add fetch_all recursive helper

- .github/workflows/Documentation.yml
- docs/src/task-spawning.md
This PR adds a section to the Task Spawning documentation page to explain the behavior observed in #548.
> add documentation for Task / Thread occupancy

- src/precompile.jl
- src/sch/Sch.jl
- src/sch/dynamic.jl
~~- Use `errormonitor_tracked()` for executing `DTask`'s~~
~~- Set `allow_errors=false` by default in the eager scheduler.~~
~~I don't know why we had `allow_errors=true` originally but it seems way too permissive, it caused some internal exceptions to not be logged when I was working on the streaming branch.~~
> Replace all uses of @async with Threads.@spawn

- docs/src/task-spawning.md
- src/Dagger.jl
- src/cancellation.jl
- src/precompile.jl
- src/sch/Sch.jl
- src/sch/eager.jl
- src/threadproc.jl
- src/utils/dagdebug.jl
- test/scheduler.jl
It's a frequent situation where a task runs for a really long time, or just hangs (maybe due to a bug, or intentionally), and we just want to stop the task and move on with life. You might think that using Ctrl+C is the right way to do this, but you'll find that with Julia (and many other languages) that this frequently does not do what you want, and is just as likely to hang or crash your Julia process. This is because the request to "cancel" some running code isn't targeted, and so Julia just interrupts whatever task is running currently, which is frequently not the task that you actually wanted to cancel.
This PR adds a new function, `Dagger.cancel!`, which allows for cancelling Dagger `DTask`s in a safe way. Unlike Ctrl+C, this doesn't force the underlying task to stop (that is …
> Add task/scheduler cancellation API

- ext/JSON3Ext.jl
- src/utils/logging.jl
Adding user defined task names #560  in visualization with `:chrome-trace` #540 . By default an automatically inferred named is used, if a task has user provided name then it will be used instead
`logs_event_pairs` is not used anymore as the `:data_annotation` are not present in it
> use user given task names in chrome trace

- .github/workflows/Documentation.yml
- docs/Project.toml
In julia 1.11 new section `[sources]` was added allowing for specifying dependencies to local or unregistered packages.
This can be used in the `docs` to specify dependencies to local packages, so the documentation can be build locally without extra tweaks
Closes #552
> Use `[sources]` to specify local deps for documentation

- .buildkite/pipeline.yml
Now we always use the latest stable and nightly builds, except for the 1.9 tests.
I also noticed that our codecov hasn't been updated for a couple years: https://app.codecov.io/gh/JuliaParallel/Dagger.jl/commits
Now that codecov doesn't allow tokenless uploading anymore I think we have to set up the `SECRET_CODECOV_TOKEN` as described here: https://github.com/JuliaGPU/buildkite?tab=readme-ov-file#using-secrets
(an admin will need to do that since I don't have access to the token)
> Update CI jobs

- docs/src/index.md
- docs/src/streaming.md
- src/dtask.jl
- src/stream.jl
- src/utils/tasks.jl
- test/streaming.jl
This defaults streaming DAGs to automatically terminate all contained tasks if any task in the DAG terminates. This ensures resources are cleaned up and tasks don't keep running in the background.
> streaming: Add DAG teardown option

- src/thunk.jl
- test/thunk.jl
Adds support for `Dagger.@spawn A -> A[3, 4] = 42.0` syntax.
> parser: Support setindex

- src/array/darray.jl
- src/array/operators.jl
- src/array/random.jl
- src/datadeps.jl
- src/thunk.jl
- test/datadeps.jl
It's incorrect to skip on just this, because we might still need to copy for the purpose of adapting types, e.g. CPU -> GPU.
> datadeps: Don't skip copy on no writedep

- src/utils/system_uuid.jl
I recently encountered a system where the `USER` environment variable got set to "domain/user". Such a name then gets interpreted as a filepath which breaks the `system_uuid_fallback` logic.
As a workaround this PR hashes the variable before using it in the filepath creation. Same user names should still result in the same hash values
> Hash `USER` environment variable during system_uuid fallback

- docs/src/index.md
as the title states, `C` is written to not read from
> docs: writes to parameter passed to Out(), doesnt read from it

- src/datadeps.jl
- test/datadeps.jl
This ensures that we take into account task scopes specified within a Datadeps region, such as:
```julia
Dagger.spawn_datadeps() do
Dagger.@spawn scope=Dagger.scope(;worker=2) myfunc!(A)
end
```
> datadeps: Support inner task scopes

- docs/src/datadeps.md
- src/memory-spaces.jl
- test/datadeps.jl
So that we can tell Datadeps that we plan to access a field/property of a structure, such as the fields of an `LU` object.
> datadeps: Support field access in Deps

- src/datadeps.jl
- src/memory-spaces.jl
- test/datadeps.jl
Also fixes unstable hashing of SubArray, which can cause `KeyError`s and other weirdness within Datadeps. And implements efficient hashing of `CartesianIndices` (used heavily with `DArray`s).
This PR should be a significant ~performance and~ correctness win.
> datadeps: Reduce dynamic dispatch with wrappers

- .buildkite/pipeline.yml
- docs/make.jl
- docs/src/index.md
- docs/src/stencils.md
- ext/CUDAExt.jl
- ext/IntelExt.jl
- ext/MetalExt.jl
- ext/OpenCLExt.jl
- ext/ROCExt.jl
- src/Dagger.jl
- src/sch/util.jl
- src/stencil.jl
- src/utils/haloarray.jl
- test/array/stencil.jl
- test/gpu.jl
- test/runtests.jl
- test/setup_gpu.jl
Adds an `@stencil` macro (and an `@neighbors` helper) for specifying stencil-like operations (such as convolutions) over one or more `DArray`s, which operate in parallel via Datadeps. For example, Conway's Game of Life can be specified as:
```julia
tiles = zeros(Blocks(N, N), Bool, N*nt, N*nt)
outputs = zeros(Blocks(N, N), Bool, N*nt, N*nt)
tiles[13, 14] = 1
tiles[14, 14] = 1
tiles[15, 14] = 1
tiles[15, 15] = 1
tiles[14, 16] = 1
import Dagger: @stencil, Wrap
Dagger.spawn_datadeps() do
@stencil begin
outputs[idx] = begin
nhood = @neighbors(tiles[idx], 1, Wrap())
neighs = sum(nhood) - tiles[idx]
if tiles[idx] && neighs < 2
0
elseif tiles[idx] && neighs > 3
0
elseif !tiles[idx] && neighs == 3
1
else
tiles[idx]
end
end
tiles[idx] = outputs[idx]
end
end
```
Todo:
> datadeps: Add at-stencil helper

- src/utils/logging.jl
As the `metrics` are expensive, while `all_task_deps` is necessary for most rendering backends.
> logging: Default disable metrics, enable all_task_deps

- docs/make.jl
- docs/src/task-affinity.md
- src/sch/Sch.jl
- src/sch/util.jl
- src/scopes.jl
- src/stream.jl
- src/thunk.jl
- test/options.jl
- test/runtests.jl
- test/scheduler.jl
- test/scopes.jl
- test/task-affinity.jl
- test/thunk.jl
- Enhanced the Thunk struct to include `compute_scope` and `result_scope` for better task execution control.
- Updated the Thunk constructor to accept new scope parameters.
- Modified the `@spawn` macro to handle the new scope parameters appropriately.
- Introduced a new test suite for task affinity, covering various scenarios with scope interactions.
- Added comprehensive documentation for task affinity, detailing the usage of `scope`, `compute_scope`, and `result_scope`.
- Implemented tests to validate behavior when using function, chunk, chunk arguments as inputs in tasks, ensuring correct scope handling.
> Add task affinity support with compute_scope and result_scope in Dagger.jl's `@spawn` macro

- docs/src/datadeps.md
- src/datadeps.jl
- src/memory-spaces.jl
- test/datadeps.jl
- Adds `view` support for efficient slicing of `DArray` chunks using standard Julia `view` syntax.  
- Introduces the `ChunkSlice` type for representing chunk subregions without materializing data.  
- Ensures robust error handling for invalid slice types and out-of-bounds indices.  
-  Documentation and Comprehensive Tests for chunk `view` functionality.
> Add `view` Support for Efficient DArray Chunk Slicing

- docs/src/darray.md
- src/array/alloc.jl
- src/array/darray.jl
- src/array/linalg.jl
- src/array/operators.jl
- test/array/allocation.jl
- test/array/linalg/core.jl
- test/runtests.jl
- Updated Distribute struct to include a processor grid for better control over data distribution.
- Modified constructors for Distribute to accept processor grid as an optional parameter.
- Enhanced distribute functions to support various assignment strategies: :arbitrary, :blockrow, :blockcol, :cyclicrow, and :cycliccol.
- Added tests for new assignment strategies, ensuring correct processor allocation and chunking for DArray, DVector, and DMatrix.
- Improved test coverage for both auto and explicit block distributions with processor assignments.
> Enhance DArray Distribution with Processor Assignment

- ext/CUDAExt.jl
- ext/IntelExt.jl
- ext/MetalExt.jl
- ext/OpenCLExt.jl
- ext/PythonExt.jl
- ext/ROCExt.jl
- src/processor.jl
- src/queue.jl
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/submission.jl
- src/threadproc.jl
- src/thunk.jl
- test/fakeproc.jl
Tasks should capture the current world age at the time of spawning, or else we might see weird behavior when code is updated midway through a computation.
> Use correct world in task execution

- .gitignore
- docs/src/darray.md
- ext/PlotsExt.jl
For easier readability and to prevent the legend from blocking view of the data itself.
> PlotsExt: Move legend to outerright of plot

- ext/CUDAExt.jl
- ext/IntelExt.jl
- ext/MetalExt.jl
- ext/OpenCLExt.jl
- ext/PythonExt.jl
- ext/ROCExt.jl
- src/processor.jl
- src/queue.jl
- src/sch/Sch.jl
- src/sch/dynamic.jl
- src/submission.jl
- src/threadproc.jl
- src/thunk.jl
- test/fakeproc.jl
Reverts JuliaParallel/Dagger.jl#652
Unfortunately, I had not considered the fact that world ages may differ between workers, so this would never have been semantically correct under distributed execution. I'll have to think harder to determine how to do world tracking correctly without killing performance...
> Revert "Use correct world in task execution"

- src/submission.jl
Fixes an evil little bug that only showed up under certain high-load situations and the right timing with the GC. Should fix any cases where we unexpectedly threw `AssertionError: No value arguments present` in `Sch.load_result`.
> submission: Reset sch_accessible for dependencies
